// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvhoffkzmcpqbulrxwls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2aG9mZmt6bWNwcWJ1bHJ4d2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzk1MTAsImV4cCI6MjA2OTgxNTUxMH0.mg06RZHKWUbLeSKT7M9zr_z4oopszUiQoqexGY2Y8WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});